project_id = "iwbdeakpqfljskpxjejm"

[functions.create-listing]
enabled = true
verify_jwt = true
import_map = "./functions/create-listing/deno.json"
entrypoint = "./functions/create-listing/index.ts"

[functions.market-snapshot]
verify_jwt = false
entrypoint = "./functions/market-snapshot/index.ts"

[functions.market-stream]
verify_jwt = false
entrypoint = "./functions/market-stream/index.ts"