// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwbdeakpqfljskpxjejm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3YmRlYWtwcWZsanNrcHhqZWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODAxMzMsImV4cCI6MjA2ODk1NjEzM30.mvShgsITnhM9XXm77PxiC0lxsbT73v_5xv3qNKONZBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});